### ISSUE TITLE
No module named 'config'

### ISSUE THREAD

**Issue by cocolord** [yanwei-li/DynamicRouting#3]
File "/home/donglusen/Workspace/DynamicRouting/tools/train_net.py", line 27, in <module>
    from config import config
ModuleNotFoundError: No module named 'config'

Is config.py missing?

**Comment by yanwei-li** [comment]
The config will be loaded from the experiment root. Please follow the procedure in README for training and testing. For example, for testing, you should `cd playground/Dynamic/Seg.Layer16` and `dl_test --num-gpus 8 MODEL.WEIGHTS /path/to/your/save_dir/ckpt.pth `

**Comment by cocolord** [comment]
> The config will be loaded from the experiment root. Please follow the procedure in README for training and testing. For example, for testing, you should `cd playground/Dynamic/Seg.Layer16` and `dl_test --num-gpus 8 MODEL.WEIGHTS /path/to/your/save_dir/ckpt.pth `

thx, config.py is loaded after changing dir.

**Comment by cocolord** [comment]
btw, when i try `dl_train MODEL.WEIGHTS Dynamic-L16B4-A73-convert-seg.pth` in the correct directory using one GPU, I found this problem:
`[04/22 21:13:17 c2.engine.train_loop]: Starting training from iteration 0
[04/22 21:13:17 c2.engine.hooks]: Total training time: 0:00:00 (0:00:00 on hooks)
Traceback (most recent call last):
  File "/home/donglusen/Workspace/DynamicRouting/tools/train_net.py", line 152, in <module>
    args=(args, ),
  File "/home/donglusen/Workspace/DynamicRouting/dl_lib/engine/launch.py", line 59, in launch
    main_func(*args)
  File "/home/donglusen/Workspace/DynamicRouting/tools/train_net.py", line 138, in main
    return trainer.train()
  File "/home/donglusen/Workspace/DynamicRouting/dl_lib/engine/custom.py", line 204, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/donglusen/Workspace/DynamicRouting/dl_lib/engine/train_loop.py", line 131, in train
    self.run_step()
  File "/home/donglusen/Workspace/DynamicRouting/dl_lib/engine/train_loop.py", line 323, in run_step
    loss_dict, flops_dict = self.model(data, iter_rate)
  File "/home/donglusen/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/donglusen/Workspace/DynamicRouting/dl_lib/modeling/meta_arch/dynamic4seg.py", line 63, in forward
    images.tensor, step_rate)
  File "/home/donglusen/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/donglusen/Workspace/DynamicRouting/dl_lib/modeling/dynamic_arch/dynamic_backbone.py", line 247, in forward
    h_l1 = self.stem(x)
  File "/home/donglusen/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/donglusen/Workspace/DynamicRouting/dl_lib/modeling/dynamic_arch/dynamic_backbone.py", line 118, in forward
    x = self.stem_1(x)
  File "/home/donglusen/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/donglusen/Workspace/DynamicRouting/dl_lib/layers/wrappers.py", line 87, in forward
    x = self.norm(x)
  File "/home/donglusen/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/donglusen/anaconda3/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 457, in forward
    world_size = torch.distributed.get_world_size(process_group)
  File "/home/donglusen/anaconda3/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 582, in get_world_size
    return _get_group_size(group)
  File "/home/donglusen/anaconda3/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 196, in _get_group_size
    _check_default_pg()
  File "/home/donglusen/anaconda3/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 187, in _check_default_pg
    "Default process group is not initialized"
AssertionError: Default process group is not initialized`
Do you have any idea about why this happened? 
This is my env info:
`sys.platform          linux
Python                3.7.4 (default, Aug 13 2019, 20:35:49) [GCC 7.3.0]
Numpy                 1.17.2
dl_lib Compiler       GCC 7.5
dl_lib CUDA Compiler  10.1
dl_lib_ENV_MODULE     <not set>
PyTorch               1.5.0
PyTorch Debug Build   False
torchvision           0.6.0
CUDA available        True
GPU 0,1               GeForce RTX 2080 Ti
CUDA_HOME             :/usr/local/cuda-10.1
Pillow                6.2.0
cv2                   4.2.0
--------------------  --------------------------------------------------`

**Comment by yanwei-li** [comment]
If a single GPU is used for training, the `NORM ` of `BACKBONE ` and `SEM_SEG_HEAD ` in the corresponding `config.py` should be changed to `"BN"`. Because Pytorch will use distributed training (require more than one GPU) if given `"nnSyncBN"`.

**Comment by cocolord** [comment]
If trained on single gpu, change syncbn to normal bn in net.py.
If trained on multi gpus, It's ok to keep conf default.
